feat: add site template
CapstoneProjectRFE2303/atelier pull request #6
Opened 2023-05-05 23:02 UTC by afrodynamic

# Pull Request Template

## Description

Adds website template for the modules required for the "product detail" page.

## Type of Change

- enhancement: new feature or request

## Checklist

- [x] I have read the [contributing guidelines](CONTRIBUTING.md) for this project.
- [x] My code follows the code style of this project.
- [-] My change requires a change to the documentation.
  - [-] I have updated the documentation accordingly.
- [-] I have added tests to cover my changes.
- [-] All new and existing tests passed.

## Reviewers

@lederius @ika-ika-ika 

## Additional Notes

`npm install` will be necessary to add "react-router-dom" to the project.

2023-05-05 23:12 UTC, ika-ika-ika requested changes
Please review comments.

2023-05-05 23:12 UTC, ika-ika-ika commented on client/src/components/ProductDetail/ProductDetail.jsx
> +import { useLocation } from 'react-router-dom';
You can move useParams and useLocation in the same line 2.

2023-05-05 23:12 UTC, ika-ika-ika commented on client/src/components/pages/ProductDetailPage.jsx
> +import { NavLink } from 'react-router-dom';
Move NavLink to line 2.

2023-05-05 23:22 UTC, afrodynamic commented on client/src/components/pages/ProductDetailPage.jsx
> +import { NavLink } from 'react-router-dom';
Fixed in 5e11f9c

2023-05-06 00:11 UTC, ika-ika-ika approved these changes
Great job!

2023-05-06 00:14 UTC, lederius approved these changes
you know its good

2023-05-06 00:19 UTC, merged